apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mario
  namespace: mario
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - mario.carsonisawesome.com
  rules:
  - host: mario.carsonisawesome.com
    http:
      paths:
      - backend:
          serviceName: mario-service
          servicePort: http
