apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mario
  namespace: mario
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - mario.carsonanderson.net
  rules:
  - host: mario.carsonanderson.net
    http:
      paths:
      - backend:
          serviceName: mario-service
          servicePort: http
