apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mario-deployment
  namespace: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-container
        image: apurvajo/mariohtml5
        resources:
          requests:
            memory: '256Mi'
            cpu: '250m'
          limits:
            memory: '1024Mi'
            cpu: '1000m'
