apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: random
  namespace: random
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - nolan.carsonanderson.net
  rules:
  - host: nolan.carsonanderson.net
    http:
      paths:
      - backend:
          serviceName: nolan-service
          servicePort: http
